name: Update XLSX to target repo

on:
  schedule:
    - cron: '51 15 * * *' # Ежедневно в 06:10 UTC (09:10 по Москве)
  workflow_dispatch:
  

jobs:
  update:
    runs-on: ubuntu-latest

    env:
      TARGET_REPO_PAT: ${{ secrets.TARGET_REPO_PAT }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install pandas requests xlrd openpyxl

    - name: Run script
      run: python server.py
